version: 2

sources:
  - name: raw_data
    schema: public   # اضافه شد
    description: "Raw data from operational system"
    tables:
      - name: raw_customers
        description: "Customer raw table from CRM"
        loaded_at_field: loaded_at
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
